#!/usr/bin/env bash

set -e

PROTOC=${1:-/usr/bin/env protoc}
export PROTOC

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROTOC_GEN_VALIDATE_LOCALES_DIR=${DIR}/../error_messages
export PROTOC_GEN_VALIDATE_LOCALES_DIR

function run_protoc() {
  set -e
  echo "Running protoc for $1"
  ${PROTOC} \
    -I=vendor/github.com/gogo/protobuf/gogoproto \
    -I=vendor/github.com/gogo/protobuf \
    -I=vendor/github.com/gogo/googleapis \
    -I=vendor/github.com/confluentinc/proto-go-setter \
    -I=vendor/github.com/travisjeffery/proto-go-sql \
    -I=vendor/github.com/envoyproxy/protoc-gen-validate \
    -I=. \
    -I=vendor \
    --sql_out=\
Msetter.proto=github.com/confluentinc/proto-go-setter,\
Msql.proto=github.com/travisjeffery/proto-go-sql,\
Mvalidate.proto=github.com/envoyproxy/protoc-gen-validate,\
Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,\
Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,\
paths=source_relative,\
plugins=grpc+embedded:. \
    --setter_out=\
Msetter.proto=github.com/confluentinc/proto-go-setter,\
Msql.proto=github.com/travisjeffery/proto-go-sql,\
Mvalidate.proto=github.com/envoyproxy/protoc-gen-validate,\
Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,\
Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,\
paths=source_relative,\
plugins=grpc+embedded:. \
    --structs_out=\
Msetter.proto=github.com/confluentinc/proto-go-setter,\
Msql.proto=github.com/travisjeffery/proto-go-sql,\
Mvalidate.proto=github.com/envoyproxy/protoc-gen-validate,\
Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,\
Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,\
paths=source_relative,\
plugins=grpc+embedded:. \
    $1
}
export -f run_protoc

function run_protoc_validate() {
  set -e
  echo "Running protoc-gen-validate for $1"
  ${PROTOC} \
     -I=./vendor/github.com/gogo/protobuf/gogoproto \
     -I=./vendor/github.com/gogo/protobuf \
     -I=./vendor/github.com/gogo/googleapis \
     -I=./vendor/github.com/confluentinc/proto-go-setter \
     -I=./vendor/github.com/travisjeffery/proto-go-sql \
     -I=./vendor/github.com/envoyproxy/protoc-gen-validate \
     -I=. \
     -I=./vendor \
    --validate_out=lang=go,\
Msetter.proto=github.com/confluentinc/proto-go-setter,\
Msql.proto=github.com/travisjeffery/proto-go-sql,\
Mvalidate.proto=github.com/envoyproxy/protoc-gen-validate,\
Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,\
Mgoogle/rpc/status.proto=github.com/gogo/googleapis/google/rpc,\
paths=source_relative,\
plugins=grpc+embedded:. \
    $1
}
export -f run_protoc_validate

# run_protoc for all these files
# NOTE: Nothing in ./common/* is being generated with this command
#       as we don't want all the gogo replace directives. We did this
#       in the previous step.
find . \
  -type d \( \
    -path "./target" -o \
    -path "./vendor" -o \
    -path "*/vendor/*" -o \
    -path "./*/util" -o \
    -path "*/mock/*" -o \
    -path "./common/*" \
  \) -prune -o \
  -type f \( \
    -name "*.proto" \
  \) \
  -print0 | \
  xargs -0 -n1 bash -c 'run_protoc "$0"'
